### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by EnforcerRyan** [lieuweberg/rich-destiny#11]
When I first launched Rich-Discord if worked to an extent but only showed "Waiting for maintenance to end" while I was in Orbit/The Enclave to test it out. Nothing. I restarted it to see if it was just bugging out, now it just says "Not playing Destiny 2" instead and i'm unsure where the error falls. Did Default installation and when restarting closed from Task Manager as the site mentioned to if it had issues, but now it just doesn't show me in game at all

![image](https://github.com/lieuweberg/rich-destiny/assets/67596550/7f2f5426-a4b8-47a7-9e97-540c583af44e)
 hope that image works to show the browser on one monitor and game on the other, obviously open. Logged in to Bungie but it shows logged in as "#" and nothing else

**Comment by lieuweberg** [comment]
Hi, do you still have this problem? If so can you please go to the support server (https://richdestiny.app/discord)? It's much easier to help you that way.
