### ISSUE TITLE
Not running on startup

### ISSUE THREAD

**Issue by ivyluma** [lieuweberg/rich-destiny#2]
Hey! I was wondering if there was some sort of control panel we needed to run before using this? It doesnt seem to have any and the only thing I can see is a logs folder and 2 .db files called "manifest" and "storage". Other than that I cannot find any other files regarding to it. Any way I can run it manually?

**Comment by lieuweberg** [comment]
https://lieuweberg.com/rich-destiny/cp is the control panel :)
