### ISSUE TITLE
How do I delete or reinstall this program?

### ISSUE THREAD

**Issue by NiceHecket** [lieuweberg/rich-destiny#3]
Hello! I accidentally deleted all files in the installation folder. Now I can't do anything with the program, because my PC thinks that it's already installed and refuses to delete the service connected to it, so I don't know how to fully delete or reinstall it.
![FQHl0xemwjo](https://user-images.githubusercontent.com/81769214/113334522-75da0a80-932c-11eb-949b-1a03c4f751a6.jpg)
Is there any way to fix this?

**Comment by lieuweberg** [comment]
If you know where you downloaded it previously, just download it to the exact same spot and restart the service from the Service manager or;
To uninstall:
 - Open an admin command prompt (not powershell) and type `sc stop rich-destiny`, and hit enter. Type `sc delete rich-destiny`, and hit enter.

**Comment by ivyluma** [comment]
Yup I figured it out! Thank you for reaching out :) Great program too!
People need to hear more about it!

**Comment by lieuweberg** [comment]
It's still not in a polished state, there are a few flaws.
