### ISSUE TITLE
Orbit getting detected as character login screen

### ISSUE THREAD

**Issue by C0D3-M4513R** [lieuweberg/rich-destiny#7]
When in Orbit the app detects the last played activity.
(I loaded into the helm and exited instantly, because the app said, that I wasn't playing d2)
```
Control Panel
Status: Social - Earth | H.E.L.M. | Warlock - 1344
Logged in as: C0D3 M4513R
Debug: 1771176108, -797199657, -547261341
Version: v0.2.4
```

When in the Character selection screen the app thinks, that you are in the Orbit.
This is in the Character selection screen.
```
Control Panel
Status: In Orbit | do stuff if you're gonna play d2 | Warlock - 1344
Logged in as: C0D3 M4513R
Debug: 82913930, -2128831035
Version: v0.2.4
```

**Comment by lieuweberg** [comment]
Nothing I can do about any of these.
You mention the app didn't detect you playing D2, but I'm a bit confused on
what you meant there since you did see a status of the helm.
Additionally, Bungie doesn't instantly clear the current activity field
from their API, so it is very normal to see some things cross over
strangely or persisting. As long as you actively play the game this shouldn't
be an issue however, only really when starting the game until you reach
orbit.

**Comment by C0D3-M4513R** [comment]
> You mention the app didn't detect you playing D2

It didn't detect me playing D2, since I installed the app, after d2 was started.
I was initially in the character selection screen, and didn't see a rich status. So I went to the control panel and clicked `reconnect to discord`, which only said something like "You are not playing destiny". When I selected a character and went into orbit, that didn't change. Only when I launched an activity(like helm) it detects. that I am playing destiny.

> Additionally, Bungie doesn't instantly clear the current activity field.
>only really when starting the game until you reach orbit.
seems a bungo thing to do.

Also after installing this my accout is now banned from destiny.
So I can't even test further.

**Comment by lieuweberg** [comment]
You didn't get banned because of rich-destiny :)

It takes about 20 seconds max before it will show your status after you have started it. It doesn't detect the game only when you launch the helm.

**Comment by C0D3-M4513R** [comment]
Since this is apparently known behavior, I'll close this for now.

**Comment by lieuweberg** [comment]
To clarify, there is no "known behaviour" anywhere in this issue apart from the starting not being instant (in case you meant something else).
