### ISSUE TITLE
[Request] Add app to PreMid

### ISSUE THREAD

**Issue by BarterClub** [lieuweberg/rich-destiny#8]
Love the idea of the app. Feel like this will get a lot more eyeballs if it's a part of PreMid that does other Discord-rich presence for a lot of different things. Not sure if it will work or not. I'll leave that up to you peeps.

**Comment by lieuweberg** [comment]
PreMiD is written in TypeScript, rich-destiny in Go. I don't have the time to -- nor do I want to -- maintain rich-destiny for PreMiD. I'm not even sure PreMiD supports programs, I can only see their store (https://github.com/PreMiD/Presences, see how the programs folder has been empty for two years) being filled with websites.

rich-destiny is designed to be the least possible burden to install, and I feel it does that job pretty well already.

EDIT: Just got a response from the PreMiD support server. PreMiD only supports websites currently. This would be impossible regardless.
